# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('C', 'C'), ('CPP', 'C++'), ('RUST', 'RUST'), ('PYTHON', 'PYTHON')], default='C', max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(max_length=20000),
        ),
    ]
