# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0002_auto_20160115_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
