# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0003_snippet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[(1, 'C'), (2, 'C++'), (3, 'RUST'), (4, 'PYTHON')], default=1, max_length=50),
        ),
    ]
