# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 05:02
from __future__ import unicode_literals

import compile_lang
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0004_auto_20160122_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[(compile_lang.SUPPORTED_LANGUAGES, 'C'), (2, 'C++'), (3, 'RUST'), (4, 'PYTHON')], default=1, max_length=50),
        ),
    ]
