# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebinapp', '0005_auto_20160122_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('C', 'C')], default='C', max_length=50),
        ),
    ]
